In [23]:
import numpy as np

In [24]:
# Create a 1D array from a list 
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [25]:
# Create a 2D array from a list 
b = np.array([[1,2],
            [3,4]])
print(b)

[[1 2]
 [3 4]]


In [26]:
# Create a 3D array from a list 
c = np.array([[[1,2], [3,4]],
            [[5,6], [7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Basic arithmetic of array operations

In [27]:
aa = np.array([[1,0,0], [1,1,1], [2,0,0]])
bb = np.array([[1,1,1], [1,1,2], [1,1,2]])

In [28]:
print(aa + bb)

[[2 1 1]
 [2 2 3]
 [3 1 2]]


In [29]:
print(aa - bb)

[[ 0 -1 -1]
 [ 0  0 -1]
 [ 1 -1 -2]]


In [30]:
print(aa * bb)

[[1 0 0]
 [1 1 2]
 [2 0 0]]


In [31]:
print(aa / bb)

[[1.  0.  0. ]
 [1.  1.  0.5]
 [2.  0.  0. ]]


### Calculating the Min, Max, and Average of an array

In [32]:
print(np.min(aa))

0


In [33]:
print(np.max(aa))

2


In [34]:
print(np.average(aa))

0.6666666666666666


### One liner solution using basic array

In [35]:
# How do we find the maximum after-tax income in a group of people, given their yearly salary and tax rate?

In [36]:
# Data: yearly salary in ($1000) [2017, 2018, 2019]
ali = [99,101,103]
bob = [110,108,105]
tim = [90,88,85]

In [37]:
salaries = np.array([ali, bob, tim])
taxation = np.array([[0.2, 0.25, 0.22],
                     [0.4, 0.50, 0.50],
                     [0.1, 0.20, 0.10]])

In [38]:
# One liner
max_income = np.max(salaries - salaries * taxation)
# Result
print(max_income) 

81.0


In [39]:
print(salaries - salaries * taxation)

[[79.2  75.75 80.34]
 [66.   54.   52.5 ]
 [81.   70.4  76.5 ]]


In [40]:
print(np.average(ali))

101.0


In [41]:
print(np.average(bob))

107.66666666666667


In [42]:
print(np.average(tim))

87.66666666666667
