### Slicing, Broadcasting, and Array Types

In [2]:
# You have data for a variety of professions, and you want to increase the salaries of just the data scientists by 10 percent every other year.

In [3]:
import numpy as np

In [4]:
# Data: yearly salary in $(1000) [2025, 2026, 2027]
dataScientist       = [130,132,137] 
productManager      = [127,140,145]
designer            = [118,118,127]
softwareEngineer    = [129,131,137] 

In [8]:
employees = np.array([dataScientist,
                      productManager,
                      designer,
                      softwareEngineer])

In [9]:
employees

array([[130, 132, 137],
       [127, 140, 145],
       [118, 118, 127],
       [129, 131, 137]])

In [10]:
# One liner 
employees[0,::2] = employees[0,::2] * 1.1

# Result
print(employees)

[[143 132 150]
 [127 140 145]
 [118 118 127]
 [129 131 137]]
